- id: toggle_christmas_lights
  alias: "Toggle Christmas Lights"
  triggers:
    - trigger: time
      at: sensor.sun_next_dawn
    - trigger: time
      at: "09:00:00"
    - trigger: time
      at: sensor.sun_next_dusk
    - trigger: time
      at: "00:00:00"
  conditions: []
  actions:
    - action: light.toggle
      metadata: {}
      target:
        entity_id: light.l930_10
      data:
        transition: 60

